-- Vider les tables
DELETE FROM ECRIRE;
DELETE FROM RESERVATIONS;
DELETE FROM PERSONNES;
DELETE FROM TITRES;


-- Script de peuplement de la table PERSONNES
INSERT INTO PERSONNES(NOM, PRENOM, EMAIL, DATENAISSANCE)
VALUES ('Sunier', 'Pierre-André', 'pa.sunier@gmail.com', NULL);

INSERT INTO PERSONNES(NOM, PRENOM, EMAIL, DATENAISSANCE)
VALUES ('Camus', 'Fabrice', 'fabrice.camus@he-arc.ch', NULL);

INSERT INTO PERSONNES(NOM, PRENOM, EMAIL, DATENAISSANCE)
VALUES ('Marée', 'Christian', NULL, NULL);

INSERT INTO PERSONNES(NOM, PRENOM, EMAIL, DATENAISSANCE)
VALUES ('Ledant', 'Guy', NULL, NULL);


-- Script de peuplement de la table TITRES
INSERT INTO TITRES(ISBN, CODEINTERNE, LIBELLE) 
VALUES ('2200214111','SQL.01','SQL 2: Initiation, programmation');

INSERT INTO TITRES(ISBN, CODEINTERNE, LIBELLE) 
VALUES ('9781540844439','MOD.02','Modèle conceptuel de données');

INSERT INTO TITRES(ISBN, CODEINTERNE, LIBELLE) 
VALUES ('9798691589386','MOD.12','Modèle physique de données relationnel: PostgreSQL');


-- Script de peuplement de la table ECRIRE
INSERT INTO ECRIRE(TIT_NUM, PERS_NUM, ESTREFERENCE)
VALUES (
	(SELECT NUM FROM TITRES WHERE (ISBN='2200214111')), 
	(SELECT NUM FROM PERSONNES WHERE (NOM='Marée')), 'Y' ); --fondamentalement pas une bonne idée


INSERT INTO ECRIRE(TIT_NUM, PERS_NUM, ESTREFERENCE)
VALUES (
	(SELECT NUM FROM TITRES WHERE (ISBN='2200214111')), 
	(SELECT NUM FROM PERSONNES WHERE (NOM='Ledant')), 'N' );

INSERT INTO ECRIRE(TIT_NUM, PERS_NUM, ESTREFERENCE)
VALUES (
	(SELECT NUM FROM TITRES WHERE (ISBN='9781540844439')), 
	(SELECT NUM FROM PERSONNES WHERE (NOM='Sunier')), 'Y' );

INSERT INTO ECRIRE(TIT_NUM, PERS_NUM, ESTREFERENCE)
VALUES (
	(SELECT NUM FROM TITRES WHERE (ISBN='9798691589386')), 
	(SELECT NUM FROM PERSONNES WHERE (NOM='Sunier')), 'Y' );

INSERT INTO ECRIRE(TIT_NUM, PERS_NUM, ESTREFERENCE)
VALUES (
	(SELECT NUM FROM TITRES WHERE (ISBN='9798691589386')), 
	(SELECT NUM FROM PERSONNES WHERE (NOM='Camus')), 'N' );

		
COMMIT;	



