ALTER SEQUENCE Personne_SEQPK CACHE 20;
ALTER SEQUENCE Titre_SEQPK CACHE 20;
ALTER SEQUENCE Ecrire_SEQPK CACHE 20;
ALTER SEQUENCE Reserv_SEQPK CACHE 20;
ALTER SEQUENCE Langue_SEQPK CACHE 20;
ALTER SEQUENCE Emprunt_SEQPK CACHE 20;
ALTER SEQUENCE Ouvrage_SEQPK CACHE 20;
